-- GENERATED by scripts/supabase-schema.ts - do not edit by hand.
-- Regenerate with: npm run supabase:schema > supabase/schema.sql
--
-- Paste into the Supabase SQL Editor and run once.
--
-- Every table is scoped to one signed-in clinic account by row-level
-- security. `owner` defaults to auth.uid(), so the app never sends it and
-- cannot spoof it.

-- --------------------------------------------------------------------------
-- vaccines
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vaccines (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  generic_name         text,
  aliases              text NOT NULL,
  unit_mode            text NOT NULL,
  doses_per_vial       bigint NOT NULL,
  min_balance_doses    bigint NOT NULL,
  is_active            bigint NOT NULL,
  sort_hint            bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.vaccines ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_vaccines_owner ON public.vaccines (owner);

DROP POLICY IF EXISTS vaccines_select ON public.vaccines;
CREATE POLICY vaccines_select ON public.vaccines
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS vaccines_insert ON public.vaccines;
CREATE POLICY vaccines_insert ON public.vaccines
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS vaccines_update ON public.vaccines;
CREATE POLICY vaccines_update ON public.vaccines
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- patients
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.patients (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  dob                  text,
  guardian_phone       text,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_patients_owner ON public.patients (owner);

DROP POLICY IF EXISTS patients_select ON public.patients;
CREATE POLICY patients_select ON public.patients
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS patients_insert ON public.patients;
CREATE POLICY patients_insert ON public.patients
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS patients_update ON public.patients;
CREATE POLICY patients_update ON public.patients
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- staff
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.staff (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  is_active            bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_staff_owner ON public.staff (owner);

DROP POLICY IF EXISTS staff_select ON public.staff;
CREATE POLICY staff_select ON public.staff
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS staff_insert ON public.staff;
CREATE POLICY staff_insert ON public.staff
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS staff_update ON public.staff;
CREATE POLICY staff_update ON public.staff
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- lots
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lots (
  id                   text PRIMARY KEY,
  vaccine_id           text NOT NULL,
  lot_number           text NOT NULL,
  expiry_date          text,
  funding_source       text NOT NULL,
  first_received_at    bigint,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.lots ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_lots_owner ON public.lots (owner);

DROP POLICY IF EXISTS lots_select ON public.lots;
CREATE POLICY lots_select ON public.lots
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS lots_insert ON public.lots;
CREATE POLICY lots_insert ON public.lots
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS lots_update ON public.lots;
CREATE POLICY lots_update ON public.lots
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- stock_movements
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id                   text PRIMARY KEY,
  idempotency_key      text NOT NULL,
  vaccine_id           text NOT NULL,
  lot_id               text,
  delta_doses          bigint NOT NULL,
  movement_type        text NOT NULL,
  wastage_reason       text,
  stock_source         text NOT NULL,
  patient_id           text,
  patient_label        text,
  staff_id             text,
  occurred_at          bigint NOT NULL,
  local_date           text NOT NULL,
  local_time           text NOT NULL,
  tz_offset_minutes    bigint NOT NULL,
  recorded_at          bigint NOT NULL,
  reverses_id          text,
  note                 text,
  needs_detail         bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_stock_movements_owner ON public.stock_movements (owner);

DROP POLICY IF EXISTS stock_movements_select ON public.stock_movements;
CREATE POLICY stock_movements_select ON public.stock_movements
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS stock_movements_insert ON public.stock_movements;
CREATE POLICY stock_movements_insert ON public.stock_movements
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- No UPDATE or DELETE policy, deliberately. The ledger is append-only on
-- the server for the same reason it is on the phone, and with RLS enabled a
-- missing policy is a denial. This is the server's half of invariant 1.

-- --------------------------------------------------------------------------
-- Sanity: this must list exactly the replicated tables.
-- expected: lots, patients, staff, stock_movements, vaccines
-- --------------------------------------------------------------------------
