-- GENERATED by scripts/supabase-schema.ts - do not edit by hand.
-- Regenerate: node scripts/supabase-schema.ts > supabase/schema.sql
--
-- Paste into the Supabase SQL Editor and run once.
--
-- Every table is scoped to one signed-in clinic account by row-level
-- security. `owner` defaults to auth.uid(), so the app never sends it and
-- cannot spoof it.

-- --------------------------------------------------------------------------
-- vaccines
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vaccines (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  generic_name         text,
  aliases              text NOT NULL,
  unit_mode            text NOT NULL,
  doses_per_vial       bigint NOT NULL,
  min_balance_doses    bigint NOT NULL,
  is_active            bigint NOT NULL,
  sort_hint            bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.vaccines ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_vaccines_owner ON public.vaccines (owner);

DROP POLICY IF EXISTS vaccines_select ON public.vaccines;
CREATE POLICY vaccines_select ON public.vaccines
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS vaccines_insert ON public.vaccines;
CREATE POLICY vaccines_insert ON public.vaccines
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS vaccines_update ON public.vaccines;
CREATE POLICY vaccines_update ON public.vaccines
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- patients
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.patients (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  dob                  text,
  guardian_phone       text,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_patients_owner ON public.patients (owner);

DROP POLICY IF EXISTS patients_select ON public.patients;
CREATE POLICY patients_select ON public.patients
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS patients_insert ON public.patients;
CREATE POLICY patients_insert ON public.patients
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS patients_update ON public.patients;
CREATE POLICY patients_update ON public.patients
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- staff
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.staff (
  id                   text PRIMARY KEY,
  name                 text NOT NULL,
  is_active            bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_staff_owner ON public.staff (owner);

DROP POLICY IF EXISTS staff_select ON public.staff;
CREATE POLICY staff_select ON public.staff
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS staff_insert ON public.staff;
CREATE POLICY staff_insert ON public.staff
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS staff_update ON public.staff;
CREATE POLICY staff_update ON public.staff
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- lots
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lots (
  id                   text PRIMARY KEY,
  vaccine_id           text NOT NULL,
  lot_number           text NOT NULL,
  expiry_date          text,
  funding_source       text NOT NULL,
  first_received_at    bigint,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  deleted_at           bigint,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.lots ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_lots_owner ON public.lots (owner);

DROP POLICY IF EXISTS lots_select ON public.lots;
CREATE POLICY lots_select ON public.lots
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS lots_insert ON public.lots;
CREATE POLICY lots_insert ON public.lots
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.
DROP POLICY IF EXISTS lots_update ON public.lots;
CREATE POLICY lots_update ON public.lots
  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

-- --------------------------------------------------------------------------
-- stock_movements
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id                   text PRIMARY KEY,
  idempotency_key      text NOT NULL,
  vaccine_id           text NOT NULL,
  lot_id               text,
  delta_doses          bigint NOT NULL,
  movement_type        text NOT NULL,
  wastage_reason       text,
  stock_source         text NOT NULL,
  patient_id           text,
  patient_label        text,
  staff_id             text,
  occurred_at          bigint NOT NULL,
  local_date           text NOT NULL,
  local_time           text NOT NULL,
  tz_offset_minutes    bigint NOT NULL,
  recorded_at          bigint NOT NULL,
  reverses_id          text,
  note                 text,
  needs_detail         bigint NOT NULL,
  created_at           bigint NOT NULL,
  updated_at           bigint NOT NULL,
  device_id            text NOT NULL,
  owner                uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  synced_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_stock_movements_owner ON public.stock_movements (owner);

DROP POLICY IF EXISTS stock_movements_select ON public.stock_movements;
CREATE POLICY stock_movements_select ON public.stock_movements
  FOR SELECT TO authenticated USING (owner = auth.uid());

DROP POLICY IF EXISTS stock_movements_insert ON public.stock_movements;
CREATE POLICY stock_movements_insert ON public.stock_movements
  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());

-- No UPDATE or DELETE policy, deliberately. The ledger is append-only on
-- the server for the same reason it is on the phone, and with RLS enabled a
-- missing policy is a denial. This is the server's half of invariant 1.

-- --------------------------------------------------------------------------
-- Uniqueness
-- --------------------------------------------------------------------------
-- One intent, one row. `idempotency_key` is deviceId:clientActionId, so
-- this is stable across devices and across retries.
CREATE UNIQUE INDEX IF NOT EXISTS ux_movements_idempotency
  ON public.stock_movements (idempotency_key);

-- A movement may be reversed AT MOST ONCE. This is what stops stock being
-- credited twice when two offline devices both correct the same entry.
CREATE UNIQUE INDEX IF NOT EXISTS ux_movements_reverses
  ON public.stock_movements (reverses_id) WHERE reverses_id IS NOT NULL;

-- Lot identity is deliberately NOT unique here, matching migration 003:
-- two devices may both log a delivery from the same batch, and rejecting a
-- real delivery to protect an index is the wrong way round. Totals stay
-- correct because stock sums movements, not lots.
CREATE INDEX IF NOT EXISTS ix_lots_identity
  ON public.lots (vaccine_id, lot_number, funding_source);

-- Vaccine name is also NOT unique here, and that is a considered choice.
-- Enforcing it would make a duplicate name reject the whole push batch, so
-- one admin mistake would stop the ledger being backed up at all. The
-- phone keeps its own UNIQUE index, and pull resolves a collision by
-- importing the loser renamed and flagging it for merge.
CREATE INDEX IF NOT EXISTS ix_vaccines_name ON public.vaccines (name);

-- --------------------------------------------------------------------------
-- Stale-write guard
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.reject_stale_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- A push is an unconditional upsert, so the newest EDIT must win here
  -- rather than the newest UPLOAD. Returning OLD silently keeps the row.
  IF NEW.updated_at < OLD.updated_at THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_vaccines_stale ON public.vaccines;
CREATE TRIGGER trg_vaccines_stale BEFORE UPDATE ON public.vaccines
  FOR EACH ROW EXECUTE FUNCTION public.reject_stale_update();

DROP TRIGGER IF EXISTS trg_patients_stale ON public.patients;
CREATE TRIGGER trg_patients_stale BEFORE UPDATE ON public.patients
  FOR EACH ROW EXECUTE FUNCTION public.reject_stale_update();

DROP TRIGGER IF EXISTS trg_staff_stale ON public.staff;
CREATE TRIGGER trg_staff_stale BEFORE UPDATE ON public.staff
  FOR EACH ROW EXECUTE FUNCTION public.reject_stale_update();

DROP TRIGGER IF EXISTS trg_lots_stale ON public.lots;
CREATE TRIGGER trg_lots_stale BEFORE UPDATE ON public.lots
  FOR EACH ROW EXECUTE FUNCTION public.reject_stale_update();

-- stock_movements is skipped: it has no UPDATE policy at all, so an
-- update cannot reach a trigger in the first place.

-- Pull reads by the SERVER clock, so this index is what makes it cheap.
CREATE INDEX IF NOT EXISTS ix_vaccines_synced ON public.vaccines (owner, synced_at);
CREATE INDEX IF NOT EXISTS ix_patients_synced ON public.patients (owner, synced_at);
CREATE INDEX IF NOT EXISTS ix_staff_synced ON public.staff (owner, synced_at);
CREATE INDEX IF NOT EXISTS ix_lots_synced ON public.lots (owner, synced_at);
CREATE INDEX IF NOT EXISTS ix_stock_movements_synced ON public.stock_movements (owner, synced_at);

-- --------------------------------------------------------------------------
-- Derived reads - MUST mirror the views in m001_initial.ts
-- --------------------------------------------------------------------------

-- Excludes reversals AND the originals they reversed. Use for ACTIVITY
-- counts ("doses given today"). Do NOT use for balances.
-- security_invoker is NOT optional. A Postgres view runs with its OWNER's
-- rights by default and therefore IGNORES row-level security, which would
-- expose every clinic to every signed-in user. This makes the view run as
-- the caller, so the policies on the underlying tables still apply.
-- DROP before CREATE, not CREATE OR REPLACE.
--
-- CREATE OR REPLACE VIEW refuses a changed column list, and the Supabase
-- SQL Editor runs this file as one transaction - so one refusal rolls back
-- everything and the view silently stays on its old definition. That is
-- exactly what happened when `level` was added. Nothing depends on these
-- views, so dropping them first is free and always works.
DROP VIEW IF EXISTS public.v_movement_effective;
CREATE VIEW public.v_movement_effective
  WITH (security_invoker = true) AS
SELECT m.* FROM public.stock_movements m
WHERE m.movement_type <> 'REVERSAL'
  AND NOT EXISTS (
    SELECT 1 FROM public.stock_movements r WHERE r.reverses_id = m.id
  );

-- Balances sum the RAW table on purpose: reversals cancel arithmetically,
-- which is the whole reason reversing entries are the right design.
DROP VIEW IF EXISTS public.v_stock_on_hand;
CREATE VIEW public.v_stock_on_hand
  WITH (security_invoker = true) AS
SELECT
  v.owner                          AS owner,
  v.id                             AS vaccine_id,
  v.name                           AS name,
  v.generic_name                   AS generic_name,
  v.unit_mode                      AS unit_mode,
  v.doses_per_vial                 AS doses_per_vial,
  v.min_balance_doses              AS min_balance_doses,
  v.is_active                      AS is_active,
  COALESCE(SUM(m.delta_doses), 0)  AS on_hand_doses,
  -- Mirrors stockLevel() in src/domain/stock.ts. Kept here rather than in
  -- the dashboard so there is ONE definition of "low": the web page must
  -- not re-derive it and quietly disagree with the phone.
  --
  -- The <= is deliberate and load-bearing. Firing at < instead means the
  -- warning never appears at exactly the safety limit, which is a silent
  -- stock-out (CLAUDE.md section 11, test 5).
  CASE
    WHEN COALESCE(SUM(m.delta_doses), 0) < 0 THEN 'NEGATIVE'
    WHEN COALESCE(SUM(m.delta_doses), 0) = 0 THEN 'OUT'
    WHEN v.min_balance_doses > 0
     AND COALESCE(SUM(m.delta_doses), 0) <= v.min_balance_doses THEN 'LOW'
    ELSE 'OK'
  END                              AS level
FROM public.vaccines v
LEFT JOIN public.stock_movements m
       ON m.vaccine_id = v.id
      AND m.owner = v.owner
      AND m.stock_source = 'CLINIC_STOCK'
WHERE v.deleted_at IS NULL
GROUP BY v.owner, v.id;

-- Per-device freshness. The dashboard leads with THIS, before any stock
-- number: a count read at home while a device has not synced for three
-- hours is wrong and looks authoritative.
DROP VIEW IF EXISTS public.v_device_activity;
CREATE VIEW public.v_device_activity
  WITH (security_invoker = true) AS
SELECT
  owner                    AS owner,
  device_id                AS device_id,
  COUNT(*)                 AS entries,
  MAX(recorded_at)         AS last_entry_at,
  MAX(synced_at)           AS last_synced_at
FROM public.stock_movements
GROUP BY owner, device_id;

GRANT SELECT ON public.v_movement_effective TO authenticated;
GRANT SELECT ON public.v_stock_on_hand      TO authenticated;
GRANT SELECT ON public.v_device_activity    TO authenticated;

-- --------------------------------------------------------------------------
-- Lock out the anonymous role entirely
-- --------------------------------------------------------------------------
-- Defence in depth, and it also makes this verifiable. Row-level security
-- already returns nothing to `anon` because every policy is TO authenticated,
-- but on an empty table "RLS is working" and "RLS is bypassed" look
-- identical from outside - both answer 200 with an empty list. Revoking the
-- grant makes `anon` answer 401 instead, so a single unauthenticated request
-- proves the clinic data is unreachable without a login.
--
-- Safe for the app: it sends the publishable key as `apikey` but also a user
-- JWT as `Authorization`, so it acts as `authenticated`, never as `anon`.
REVOKE ALL ON public.vaccines FROM anon;
REVOKE ALL ON public.patients FROM anon;
REVOKE ALL ON public.staff FROM anon;
REVOKE ALL ON public.lots FROM anon;
REVOKE ALL ON public.stock_movements FROM anon;
REVOKE ALL ON public.v_movement_effective FROM anon;
REVOKE ALL ON public.v_stock_on_hand      FROM anon;
REVOKE ALL ON public.v_device_activity    FROM anon;

-- Verify security_invoker really took effect. Every row must show
-- security_invoker=true; a NULL means the view runs as its OWNER and
-- ignores row-level security, which would expose every clinic.
--   SELECT c.relname, c.reloptions
--     FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
--    WHERE n.nspname = 'public' AND c.relkind = 'v';

-- --------------------------------------------------------------------------
-- Sanity: this must list exactly the replicated tables.
-- expected: lots, patients, staff, stock_movements, vaccines
-- --------------------------------------------------------------------------
