import { openNodeDb } from '../src/db/driver.node.ts';
// Imported directly, with explicit extensions: `migrate.ts` pulls in the
// migrations DIRECTORY, and Node's ESM resolver rejects a directory import.
// Same workaround as scripts/dump-schema.ts.
import { m001 } from '../src/db/migrations/m001_initial.ts';
import { m002, PUSH_ORDER, SYNC_TABLES } from '../src/db/migrations/m002_sync.ts';

/**
 * Generate the Supabase (Postgres) schema FROM the live SQLite schema.
 *
 * Hand-typing it is the obvious way to do this and the wrong one: PostgREST
 * rejects an unknown column with a 400, so a single missed column silently
 * breaks every push of that table. Generating from PRAGMA table_info means the
 * two cannot drift, and re-running this after a future migration produces the
 * exact ALTER TABLE surface that migration needs.
 *
 *   npm run supabase:schema > supabase/schema.sql
 */

interface Col { name: string; type: string; notnull: number; dflt_value: string | null; pk: number }

/** These are this phone's bookkeeping, not clinic data. Never uploaded. */
const LOCAL_ONLY = new Set(['dirty', 'last_synced_at']);

function pgType(sqliteType: string): string {
  const t = sqliteType.toUpperCase();
  if (t.startsWith('INT')) return 'bigint';
  return 'text';
}

const main = async () => {
  const db = openNodeDb(':memory:');
  await db.exec('PRAGMA foreign_keys = ON');
  await db.tx(async (tx) => {
    await m001.up(tx);
    await m002.up(tx);
  });

  const out: string[] = [];
  out.push('-- GENERATED by scripts/supabase-schema.ts - do not edit by hand.');
  out.push('-- Regenerate with: npm run supabase:schema > supabase/schema.sql');
  out.push('--');
  out.push('-- Paste into the Supabase SQL Editor and run once.');
  out.push('--');
  out.push('-- Every table is scoped to one signed-in clinic account by row-level');
  out.push('-- security. `owner` defaults to auth.uid(), so the app never sends it and');
  out.push('-- cannot spoof it.');
  out.push('');

  for (const table of PUSH_ORDER) {
    const cols = (await db.all<Col>(`PRAGMA table_info(${table})`)).filter(
      (c) => !LOCAL_ONLY.has(c.name),
    );

    out.push(`-- ${'-'.repeat(74)}`);
    out.push(`-- ${table}`);
    out.push(`-- ${'-'.repeat(74)}`);
    out.push(`CREATE TABLE IF NOT EXISTS public.${table} (`);
    const lines = cols.map((c) => {
      const nn = c.notnull ? ' NOT NULL' : '';
      const pk = c.pk ? ' PRIMARY KEY' : '';
      return `  ${c.name.padEnd(20)} ${pgType(c.type)}${pk}${pk ? '' : nn}`;
    });
    lines.push(`  ${'owner'.padEnd(20)} uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id)`);
    lines.push(`  ${'synced_at'.padEnd(20)} timestamptz NOT NULL DEFAULT now()`);
    out.push(lines.join(',\n'));
    out.push(');');
    out.push('');
    out.push(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;`);
    out.push(`CREATE INDEX IF NOT EXISTS ix_${table}_owner ON public.${table} (owner);`);
    out.push('');
    out.push(`DROP POLICY IF EXISTS ${table}_select ON public.${table};`);
    out.push(`CREATE POLICY ${table}_select ON public.${table}`);
    out.push(`  FOR SELECT TO authenticated USING (owner = auth.uid());`);
    out.push('');
    out.push(`DROP POLICY IF EXISTS ${table}_insert ON public.${table};`);
    out.push(`CREATE POLICY ${table}_insert ON public.${table}`);
    out.push(`  FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());`);
    out.push('');

    if (table === 'stock_movements') {
      out.push('-- No UPDATE or DELETE policy, deliberately. The ledger is append-only on');
      out.push('-- the server for the same reason it is on the phone, and with RLS enabled a');
      out.push("-- missing policy is a denial. This is the server's half of invariant 1.");
      out.push('');
    } else {
      out.push(`-- Mutable tables: the phone re-pushes an edited row, so allow the overwrite.`);
      out.push(`DROP POLICY IF EXISTS ${table}_update ON public.${table};`);
      out.push(`CREATE POLICY ${table}_update ON public.${table}`);
      out.push(`  FOR UPDATE TO authenticated USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());`);
      out.push('');
    }
  }

  out.push(`-- ${'-'.repeat(74)}`);
  out.push('-- Sanity: this must list exactly the replicated tables.');
  out.push(`-- expected: ${[...SYNC_TABLES].sort().join(', ')}`);
  out.push(`-- ${'-'.repeat(74)}`);
  console.log(out.join('\n'));
};

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
